#!/bin/bash
# Purpose: Submit both iOS and macOS builds using ReleaseTools and push tags.
# Usage: Extras/Scripts/upload

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 25/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

set -euo pipefail  # (add an x to flags to enable debugging)

echo " "
echo "**********"
echo "Submitting"
echo "**********"

rt tag

echo "--------------"
echo "Submitting iOS"
echo "--------------"

rt submit --platform=iOS


echo " "
echo "----------------"
echo "Submitting macOS"
echo "----------------"

rt submit --platform=macOS

echo "------------"
echo "Pushing Tags"
echo "------------"

git push --tags --force

echo "-----------------"
echo "Opening App Store"
echo "-----------------"

open "https://appstoreconnect.apple.com/teams/69a6de8a-ccc2-47e3-e053-5b8c7c11a4d1/apps/1519213388/testflight/ios"
